### ISSUE TITLE
練習問題2.10の訳文について

### ISSUE THREAD

**Issue by so-nakashima** [hiroshi-manabe/sicp-pdf#12]
はじめまして。
練習問題2.10の問題文に「長さがゼロの区間で割る」とありますが、原文では”divide by an interval that spans zero”となっています。spanの意味、および訳文だと問題が解けない（長さ0の区間で割ることには問題はない）ことから、ここは「0をまたぐ区間で割る」が正しいと思います。

**Comment by hiroshi-manabe** [comment]
ご報告ありがとうございます。
ここはちょっと手ごわそうだったので、翻訳時に自分で練習問題を解かずに訳していて、その結果「長さがゼロの区間で割る」ことができないのだろうと推測し、それに合わせて翻訳してしまいました。
よく読むとそうではないですね。span の語義からもおっしゃる通りです。
先ほど修正してファイルを更新しました。
