### ISSUE TITLE
練習問題2.65の訳について

### ISSUE THREAD

**Issue by xenolay** [hiroshi-manabe/sicp-pdf#14]
はじめまして．

練習問題2.65の訳についてです．原文は，
"Use the results of exercises 2.63 and 2.64 to give \Theta (n) implementations of union-set
and intersection-set for sets implemented as (balanced) binary trees."とありますが，訳において「union-setとintersection-setを実装せよ」という旨の記述が欠落し，問題設定が不明瞭になっているように思われます．ご検討よろしくお願いします．

**Comment by hiroshi-manabe** [comment]
ありがとうございます。うっかりしていました。修正します。
