### ISSUE TITLE
341頁の訳について

### ISSUE THREAD

**Issue by so-nakashima** [hiroshi-manabe/sicp-pdf#16]
341頁の本文最終行の訳が「a2 を保護する直列化手続きからPeter が抜けるまで、Peter は進む(a2 を保護する直列化手続きに入る) ことができません」となっていますが、意味と原著から考えると「Paulが抜けるまで、Peterは進むことができません。」が正しいと思います。

**Comment by hiroshi-manabe** [comment]
ありがとうございます。修正しました。
