### ISSUE TITLE
練習問題1.45の訳について

### ISSUE THREAD

**Issue by ghost** [hiroshi-manabe/sicp-pdf#21]
はじめまして。

原文: "Use this to implement a simple procedure for computing nth roots using fixed-point, average-damp, and the repeated procedure of exercise 1.43."

訳: "その結果を利用し、練習問題 1.43の fixed-point, average-damp, repeated 手続きを使って n 乗根を計算する単独の手続きを実装せよ。"

となっていますが、"fixed-point, average-damp および練習問題 1.43の repeated 手続きを使って〜" と訳すのが正しいと思います。

**Comment by hiroshi-manabe** [comment]
ありがとうございます。修正しました。
