### ISSUE TITLE
練習問題4.36の訳について

### ISSUE THREAD

**Issue by ghost** [hiroshi-manabe/sicp-pdf#26]
minghaiさんの誤訳の修正漏れです。

原文: "Explain why simply replacing an-integer-between by an-integer-starting-from in the procedure in exercise 4.35 is not an adequate way to generate arbitrary Pythagorean triples. "

訳: "an-integer-between を単純に練習問題 4.35の手続き内の an-integer-starting-from で置き換えるというやり方が、任意のピタゴラス数を生成する方法としてなぜ適切でないのか説明せよ。"

"the procedure in exercise 4.35"とは、具体的には練習問題 4.35で定義されている a-pythagorean-triple-between のことだと思いますので上の訳は間違いです。

"単純に練習問題 4.35の手続き内の an-integer-between を an-integer-starting-from で置き換えるというやり方が〜"などと訳すのが正しいと思います。

**Comment by hiroshi-manabe** [comment]
ありがとうございます。概ねご提案の通り修正しました。
